version: 2.1

orbs:
  node: circleci/node@5.0

executors:
  node:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.18

commands:
  restorecache:
    description: "Loads npm package cache"
    steps:
      - restore_cache:
          keys:
            - node-v3-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v3-{{ .Branch }}-
            - node-v3-

  savecache:
    description: "Saves npm packages to cache"
    steps:
      - save_cache:
          key: node-v3-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restorecache
      - run: npm ci
      - savecache

  test:
    executor: node
    steps:
      - run: npm run test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
